#!/usr/bin/env python
from TwitterAPI import TwitterAPI, TwitterConnectionError
from app import config
from app.database import Database
from app.pubsub import PubSub
import os

api = TwitterAPI(config.CONSUMER_KEY,
                 config.CONSUMER_SECRET,
                 config.ACCESS_TOKEN_KEY,
                 config.ACCESS_TOKEN_SECRET)

ps = PubSub()

db = Database(config.DBURI, config.DEBUG, drop_all=config.TRUNCATE_TABLES)

while True:
    try:
        # Get an API handler
        r = api.request("statuses/filter", {"locations": config.BBOX})

        for item in r:
            if "coordinates" in item and item["coordinates"] is not None:
                tweet = db.insert_tweet(item)
                if tweet is not None:
                    ps.publish(tweet)
            elif "disconnect" in item:
                pass

    except TwitterConnectionError as e:
        print "Connection Error!"
