#!/usr/bin/env python
from TwitterAPI import TwitterAPI, TwitterConnectionError
from app.database import database
import os, sys

# Define API keys
CONSUMER_KEY = os.environ["CONSUMER_KEY"]
CONSUMER_SECRET = os.environ["CONSUMER_SECRET"]
ACCESS_TOKEN_KEY = os.environ["ACCESS_TOKEN_KEY"]
ACCESS_TOKEN_SECRET = os.environ["ACCESS_TOKEN_SECRET"]
BBOX = os.environ["BBOX"]
DBURI = os.environ["DBURI"]

api = TwitterAPI(CONSUMER_KEY,
                 CONSUMER_SECRET,
                 ACCESS_TOKEN_KEY,
                 ACCESS_TOKEN_SECRET)

debug = False
if "DEBUG" in os.environ and int(os.environ["DEBUG"]):
    debug = True

db = database.Database(DBURI, debug)

while True:
    try:
        # Get an API handler
        r = api.request("statuses/filter", {"locations": BBOX})

        for item in r:
            if item["coordinates"] is not None:
                db.insert(item)
            elif "disconnect" in item:
                pass

    except TwitterConnectionError as e:
        # Connection error - retry request
        pass